export const buttonsMap: { [key: string]: string } = {
    新增: "add",
    编辑: "edit",
    查看: "view",
    删除: "delete",
    移除: "delete",
    新建项目: "addProject",
    成员管理: "memberManage",
    标注空间: "dataSetSpace",
    添加成员: "addUser",
    新建账户: "addUser",
    批量移除: "batchUser",
    修改角色: "editUserRole",
    配额: "quota",
    创建资源规格: "creatingResourceSpecification",
    Notebook默认镜像设置: "defaultSetting",
    创建镜像: "createImage",
    下载: "download",
    新建组织机构: "addOrganization",
    导入: "import",
    启用: "enable",
    禁用: "disable",
};
